# Draculinho for btop. Dracula, a few shades darker.

theme[main_bg]="#0E131B"
theme[main_fg]="#CDD0DD"
theme[title]="#CDD0DD"
theme[hi_fg]="#BD93F9"
theme[selected_bg]="#44475A"
theme[selected_fg]="#CDD0DD"
theme[inactive_fg]="#7a86ad"
theme[graph_text]="#CDD0DD"
theme[meter_bg]="#21222C"
theme[proc_misc]="#BD93F9"

theme[cpu_box]="#BD93F9"
theme[mem_box]="#3dcf62"
theme[net_box]="#FF5555"
theme[proc_box]="#00B5DC"
theme[div_line]="#1c2636"

theme[temp_start]="#BD93F9"
theme[temp_mid]="#FF79C6"
theme[temp_end]="#FF5555"

theme[cpu_start]="#BD93F9"
theme[cpu_mid]="#00B5DC"
theme[cpu_end]="#3dcf62"

theme[free_start]="#ffb3de"
theme[free_mid]="#FF79C6"
theme[free_end]="#e0479f"

theme[cached_start]="#7fdcf0"
theme[cached_mid]="#00B5DC"
theme[cached_end]="#0089a8"

theme[available_start]="#ffd4a6"
theme[available_mid]="#FFB86C"
theme[available_end]="#e08f33"

theme[used_start]="#8fe8a5"
theme[used_mid]="#3dcf62"
theme[used_end]="#22a544"

theme[download_start]="#BD93F9"
theme[download_mid]="#00B5DC"
theme[download_end]="#3dcf62"

theme[upload_start]="#8c42ab"
theme[upload_mid]="#FF79C6"
theme[upload_end]="#FF5555"

theme[process_start]="#3dcf62"
theme[process_mid]="#E2DD61"
theme[process_end]="#FF5555"
