name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited

jobs:
  check_sv:
    name: Check Semantic Version PR
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: amannn/action-semantic-pull-request@v4